version: "3"

# volumes:
#   pgdatasource:

services:
  gatekiosk-db:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_PORT=5432
      - POSTGRES_DB=gatekiosk
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    #   - pgdatasource:/var/lib/postgresql/data

  gatekiosk-api:
    build: api/
    depends_on:
      gatekiosk-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=gatekiosk-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    # volumes:
    #   - type: bind
    #     source: ./api
    #     target: /app
    command: npm run start
    restart: on-failure
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 5s
      timeout: 5s
      start_period: 120s
      retries: 10

  gatekiosk-ui:
    build: ui/
    depends_on:
      - "gatekiosk-api"
    ports:
      - "3001:3000"
    volumes:
      - type: bind
        source: ./ui/src
        target: /app
    restart: on-failure
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 5s
      timeout: 5s
      start_period: 120s
      retries: 10
